export const IMAGES = {
  Splash: require('../assets/images/Splash.png'),
  Background: require('../assets/images/Background.png'),
  Card: require('../assets/images/Card.png'),
  BigCard: require('../assets/images/big_card.png'),
  Banner: require('../assets/images/banner.png'),
  Offer: require('../assets/images/offer.png'),
  Booking: require('../assets/images/booking.png'),
  Tabbar: require('../assets/images/tabbar.png'),
  NoInternet: require('../assets/images/no-internet.png'),
  Camera: require('../assets/images/camera.png'),
  Gallery: require('../assets/images/photo-gallery.png'),
  Close: require('../assets/images/close-window.png'),
  NoData: require('../assets/images/no_data.png'),
};
